#!/bin/sh
# start trayer, setup xrandr
BG=~/lambda/business/lambda-labs-logo_180x180_black.png

if [ -x /usr/bin/trayer ]
then
	trayer --edge top --align right --SetDockType true \
		--SetPartialStrut true --expand true --width 10 \
		--transparent true --tint 0x000000 --height 12 &>/dev/null &
fi
if [ -x /usr/bin/nm-applet ]
then
	sudo nm-applet &> /dev/null &
fi

if [ -x /usr/bin/xrandr ]
then
	xrandr --output DVI-I-2 --rotate left --auto --left-of DVI-I-3 --auto
	xrandr --output DVI-I-3 --rotate left --auto --right-of DVI-I-2 --auto
	xrandr --output HDMI-0 --auto --right-of DVI-I-3 --auto
fi

if [ -x /usr/bin/feh ]
then
	feh --bg-center $BG
fi
