#!/bin/sh
# start trayer, setup xrandr
BG=~/lambda/business/lambda-labs-logo_180x180_black.png
# trayer --edge bottom --align center --SetDockType true --SetPartialStrut true --expand true --width 5 --height 18 --transparent true --alpha 155 &>/dev/null &

trayer --edge top --align right --SetDockType true --SetPartialStrut true \
	 --expand true --width 10 --transparent true --tint 0x000000 --height 12 &>/dev/null &
if [ -x /usr/bin/nm-applet ]
then
	sudo nm-applet &> /dev/null &
fi

if [ -x /usr/bin/feh ]
then
	feh --bg-center $BG
fi
xrandr --output DP1 --mode 1920x1080 --right-of eDP1
