#!/bin/bash
SCRIPTDIR=`dirname $0`
DATEYEAR=`date +%Y`
CREATION=`date "+%Y-%m-%d %H:%M:%S %z"`
if [[ $1 ]]; then
    FILETEXT="    $1
    $(printf '~%.0s' $(seq 1 $(($(echo $1 | wc -c) - 1))))"
else
    FILETEXT=""
fi;
source $SCRIPTDIR/script_env

function pheadEcho {
    echo "#!/usr/bin/env python"
    echo "\"\"\"
$FILETEXT

    :created: $CREATION
    :copyright: (c) $DATEYEAR, $ENTITY
    :license: $LICENSE_DESC
\"\"\"
"
}

pheadEcho
