#!/bin/bash
# https://coderwall.com/p/trgyrq

LSEP=|
LSEPE=
RSEP=|
RSEPE=|

CALENDAR=
BATTERY_PRE=B
DATETIME=⌚
MUSIC=♫

WIDTH=${1}

SMALL=80
MEDIUM=140

if [[ "$WIDTH" -gt "$MEDIUM" ]]
then
# $MUSIC $(mpc current)"
  MPD="#[fg=colour252,bg=default,nobold,noitalics,nounderscore]$RSEP#[fg=colour16,bg=colour252,bold,noitalics,nounderscore]"
  date_colour='colour252'
fi

if [[ "$WIDTH" -ge "$SMALL" ]]; then
  UNAME="#[fg=colour252,bg=colour236,nobold,noitalics,nounderscore]$RSEP#[fg=colour16,bg=colour252,bold,noitalics,nounderscore] $(uname -n)"
fi
DATETIME="$CALENDAR $(date +'%Y-%m-%d %H:%M')"
BATTERY="$BATTERY_PRE $(battery_life.sh)"

echo "$MPD $BATTERY $DATETIME $UNAME " | sed 's/ *$/ /g'
